### PR TITLE
Work in progress: Apply Codecs to StableStore

### PR DESCRIPTION
**Pull request by kula**
Mostly throwing this out there for discussion

### CODE REVIEW

**Comment by banks** [comment]
@kula did you have a use-case in mind that would need custom encoding for these? The `StableStore` API is fixed and opaque - values are either uint64 or arbitrary bytes so I'm not super sure why you'd even need to encode those two type differently?

**Comment by kula** [comment]
> @kula did you have a use-case in mind that would need custom encoding for these? The `StableStore` API is fixed and opaque - values are either uint64 or arbitrary bytes so I'm not super sure why you'd even need to encode those two type differently?

@banks I have some preliminary work for the `LogStore` where I'm writing a Codec to encrypt everything in the log, and had in mind being able to point at the `StableStore` and go "see, everything in there is encrypted too". Not that I can remember off hand what else I was going to put in `StableStore` beyond what `hashicorp/raft` already does (which is pretty innocuous and doesn't really need encrypting). It's been a while since I've done any work on that project, and honestly can't remember if I had a valid use case for this or was just falling down a rabbit hole.

**Comment by banks** [comment]
Ah got it.

>  Not that I can remember off hand what else I was going to put in StableStore beyond what hashicorp/raft already does (which is pretty innocuous and doesn't really need encrypting).

Yeah it's just two ints and the name of the server that was last voted for so IMO not worth encrypting generally. This interface _could_ be used for more but I doubt it would be by our raft implementation any time soon...

**Comment by banks** [comment]
Also, I'd probably instead suggest that if you want to encrypt the `MetaStore` you do so by just building a custom `MetaStore` that does the encryption inside rather than the added complexity of adding another Codec interface etc. It could even wrap the existing BoltDB `MetaStore` and just wrap each Set/Get command in encruption? That way you could even encrypt the WAL segment meta data too if you so wanted!

What do you think?

**Comment by kula** [comment]
I think that makes sense, on reflection. Codecs on `LogStore` make sense because it allows you to define how bits are written to disk, insert things like crypto, but still maintain all of the semantic guarantees the WAL is offering in terms of correctness, crash safety, etc. And the potential use cases I'd have with needing a place to stash small bits of data, should I need to encrypt them, could as you suggest be stored in a complimentary `MetaStore`-like thing which sits along side the one WAL uses (or even just uses another bucket within the existing `MetaStore`) and has methods which do whatever I want with respect to the data as it passes through.

**Pull request closed without merging**
